// @ts-nocheck
// Sample UI translations. Production linguistic review remains required.
// win, settings, count-up, close, dialog, language, currency, amount, mobile, title, note
const sampleTranslations={
en:['WIN','Settings','Preview count-up','Close','Typography and icon preview.','Language','Currency','Amount','Mobile width','UI lettering sample','Visual sample only; no bets. The arrow animates the amount. Currency does not change with language. Fonts and translations await production review.'],
ar:['الأرباح','الإعدادات','معاينة العد التصاعدي','إغلاق','معاينة الخط والأيقونات.','اللغة','العملة','المبلغ','عرض الهاتف','نموذج خطوط الواجهة','نموذج مرئي فقط؛ لا توجد رهانات. يعرض السهم حركة المبلغ. لا تتغير العملة بتغيير اللغة. الخطوط والترجمات قيد المراجعة قبل الإصدار.'],
de:['GEWINN','Einstellungen','Zählanimation ansehen','Schließen','Vorschau für Schrift und Symbole.','Sprache','Währung','Betrag','Mobilbreite','Schriftvorschau der Oberfläche','Nur eine visuelle Vorschau; keine Einsätze. Der Pfeil animiert den Betrag. Die Währung bleibt beim Sprachwechsel gleich. Schriftarten und Übersetzungen müssen vor Veröffentlichung geprüft werden.'],
es:['PREMIO','Ajustes','Ver animación del importe','Cerrar','Vista previa de tipografía e iconos.','Idioma','Moneda','Importe','Ancho móvil','Muestra de tipografía de la interfaz','Solo una muestra visual; sin apuestas. La flecha anima el importe. La moneda no cambia con el idioma. Las fuentes y traducciones están pendientes de revisión antes de publicarse.'],
fi:['VOITTO','Asetukset','Esikatsele summan kasvua','Sulje','Kirjasinten ja kuvakkeiden esikatselu.','Kieli','Valuutta','Summa','Mobiilileveys','Käyttöliittymän tekstinäyte','Vain visuaalinen näyte; ei panoksia. Nuoli animoi summan. Valuutta ei muutu kielen mukana. Kirjasimet ja käännökset tarkistetaan ennen julkaisua.'],
fr:['GAIN','Paramètres','Aperçu du compteur','Fermer','Aperçu de la typographie et des icônes.','Langue','Devise','Montant','Largeur mobile','Aperçu du lettrage de l’interface','Aperçu visuel uniquement ; aucune mise. La flèche anime le montant. La devise ne change pas avec la langue. Les polices et traductions restent à vérifier avant publication.'],
hi:['जीत','सेटिंग्स','बढ़ती राशि का पूर्वावलोकन','बंद करें','फ़ॉन्ट और आइकन का पूर्वावलोकन।','भाषा','मुद्रा','राशि','मोबाइल चौड़ाई','इंटरफ़ेस अक्षरों का नमूना','केवल दृश्य नमूना; कोई दाँव नहीं। तीर राशि को एनिमेट करता है। भाषा बदलने पर मुद्रा नहीं बदलती। प्रकाशन से पहले फ़ॉन्ट और अनुवाद की समीक्षा होनी है।'],
id:['KEMENANGAN','Pengaturan','Pratinjau hitungan naik','Tutup','Pratinjau tipografi dan ikon.','Bahasa','Mata uang','Jumlah','Lebar ponsel','Contoh huruf antarmuka','Hanya contoh visual; tanpa taruhan. Panah menganimasikan jumlah. Mata uang tidak berubah saat bahasa diganti. Font dan terjemahan perlu ditinjau sebelum rilis.'],
ja:['獲得額','設定','カウントアップを確認','閉じる','文字とアイコンのプレビューです。','言語','通貨','金額','モバイル幅','UI文字のサンプル','表示サンプルのみで、賭けは行いません。矢印で金額のアニメーションを確認できます。言語を変えても通貨は変わりません。公開前にフォントと翻訳の確認が必要です。'],
ko:['당첨금','설정','금액 증가 미리 보기','닫기','글꼴과 아이콘 미리 보기입니다.','언어','통화','금액','모바일 너비','UI 글자 샘플','시각적 샘플이며 베팅은 없습니다. 화살표를 누르면 금액이 움직입니다. 언어를 변경해도 통화는 바뀌지 않습니다. 출시 전에 글꼴과 번역을 검토해야 합니다.'],
pl:['WYGRANA','Ustawienia','Podgląd naliczania','Zamknij','Podgląd typografii i ikon.','Język','Waluta','Kwota','Szerokość mobilna','Próbka napisów interfejsu','Tylko podgląd wizualny; bez zakładów. Strzałka animuje kwotę. Waluta nie zmienia się wraz z językiem. Czcionki i tłumaczenia wymagają weryfikacji przed publikacją.'],
pt:['PRÊMIO','Configurações','Prévia da contagem','Fechar','Prévia da tipografia e dos ícones.','Idioma','Moeda','Valor','Largura de celular','Amostra de letras da interface','Apenas uma amostra visual; sem apostas. A seta anima o valor. A moeda não muda com o idioma. As fontes e traduções precisam de revisão antes do lançamento.'],
ru:['ВЫИГРЫШ','Настройки','Просмотр подсчёта','Закрыть','Предпросмотр шрифтов и значков.','Язык','Валюта','Сумма','Ширина телефона','Образец текста интерфейса','Только визуальный образец; без ставок. Стрелка запускает анимацию суммы. Валюта не меняется при смене языка. Шрифты и переводы требуют проверки перед выпуском.'],
tr:['KAZANÇ','Ayarlar','Artan tutarı önizle','Kapat','Yazı tipi ve simge önizlemesi.','Dil','Para birimi','Tutar','Mobil genişlik','Arayüz yazı örneği','Yalnızca görsel örnek; bahis yapılmaz. Ok, tutarı canlandırır. Dil değiştiğinde para birimi değişmez. Yazı tipleri ve çeviriler yayımlanmadan önce incelenmelidir.'],
vi:['TIỀN THẮNG','Cài đặt','Xem hiệu ứng đếm tiền','Đóng','Xem trước kiểu chữ và biểu tượng.','Ngôn ngữ','Tiền tệ','Số tiền','Chiều rộng di động','Mẫu chữ giao diện','Chỉ là bản mẫu hình ảnh; không đặt cược. Nút mũi tên chạy hiệu ứng số tiền. Đổi ngôn ngữ không đổi tiền tệ. Phông chữ và bản dịch cần được kiểm tra trước khi phát hành.'],
zh:['赢取金额','设置','预览金额递增','关闭','字体和图标预览。','语言','货币','金额','手机宽度','界面文字示例','仅供视觉预览，不会下注。箭头按钮演示金额动画。切换语言不会改变货币。字体和翻译须在发布前审核。'],
da:['GEVINST','Indstillinger','Forhåndsvis optælling','Luk','Forhåndsvisning af skrifttyper og ikoner.','Sprog','Valuta','Beløb','Mobilbredde','Eksempel på grænsefladetekst','Kun et visuelt eksempel; ingen indsatser. Pilen animerer beløbet. Valutaen ændres ikke med sproget. Skrifttyper og oversættelser skal gennemgås før udgivelse.']
};

export default sampleTranslations;
